POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Roshith",
    "number": "4-67504540"
}

###

GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/64986ba5ecf4605873d01226

###

PUT http://localhost:3001/api/persons/649bf72f2ca724a1aadbf66a
Content-Type: application/json

{
    "number": 8840975678
}

###

DELETE http://localhost:3001/api/persons/649c28139eb89891ff117358

